name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Flet Build Tool
        run: |
          pip install --upgrade pip
          pip install flet

      - name: Build Android APK
        run: |
          flet build apk --project-name "MangaBinder"
          
